version: '3'

volumes:
  mongodb_data: {}

services:
  api:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: keeper_backend
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    env_file:
      - .envs/.local
    ports:
      - '8090:8090'
    command: uvicorn api.main:app --reload --port 8090 --host 0.0.0.0

  mongodb:
    image: mongo:4.4.3-bionic
    env_file:
      - .envs/.local
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: keeper_frontend
    env_file:
      - .envs/.local
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '3000:3000'
    command: "yarn run start"
