version: '2'

volumes:
  mongodb_data: {}

services:
  api:
    image: ghcr.io/nihisil/keeper_backend:latest
    depends_on:
      - mongodb
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    env_file:
      - .envs/.production
    ports:
      - '8090:8090'
    command: uvicorn api.main:app --workers 2 --port 8090 --host 0.0.0.0

  cron:
    image: keeper_backend
    depends_on:
      - mongodb
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    env_file:
      - VERSION
      - .envs/.local
    volumes:
      - ./backend:/app
    user: root
    command: [ 'crond', '-l', '0', '-d', '0', '-f' ]

  mongodb:
    image: mongo:4.4.4-bionic
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    env_file:
      - .envs/.production
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth --quiet
