version: '3'

volumes:
  keeper_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: keeper_web
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .envs/.local
    ports:
      - '8050:8050'
    command: python manage.py runserver 0.0.0.0:8050

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: keeper_frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'

  db:
    image: postgres:13.1-alpine
    env_file:
      - .envs/.local
    volumes:
      - keeper_postgres_data:/var/lib/postgresql/data
    ports:
      - '8900:5432'
