version: '3'

services:
  api:
    env_file:
      - .envs/.local
      - .envs/.test
  cypress:
    image: "cypress/included:7.0.0"
    depends_on:
      - api
      - frontend
    env_file:
      - .envs/.test
    working_dir: /e2e
    volumes:
      - ./frontend/:/e2e
