version: '3'

volumes:
  local_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: keeper_web
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .envs/.local
      - .envs/.postgres
    ports:
      - '8050:8050'
    command: /start

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: life_local_postgresql
    env_file:
      - .envs/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - '8900:5432'
