version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: keeper_backend
    volumes:
      - ./backend:/app
    env_file:
      - .envs/.local
    ports:
      - '8090:8090'
    command: uvicorn api.main:app --reload --port 8090 --host 0.0.0.0

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: keeper_frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
