# Generated by Django 3.0.3 on 2020-03-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200309_0253'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[[0, 'Goodreads'], [1, 'Fantlab'], [2, 'Librarything']])),
                ('external_id', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Language')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Language')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Series')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='seriesbookitem',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Series'),
        ),
        migrations.AlterField(
            model_name='shelfbookitem',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Shelf'),
        ),
    ]
