# Generated by Django 3.0.3 on 2020-03-09 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200309_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesversion',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='book.Series'),
        ),
    ]
