# Generated by Django 3.0.3 on 2020-03-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200309_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorversion',
            options={'ordering': ['language__order']},
        ),
        migrations.AlterModelOptions(
            name='bookversion',
            options={'ordering': ['language__order']},
        ),
        migrations.RenameField(
            model_name='seriesversion',
            old_name='series',
            new_name='entity',
        ),
        migrations.RemoveField(
            model_name='authorversion',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='authorversion',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='book.Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookversion',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='book.Book'),
            preserve_default=False,
        ),
    ]
