# Generated by Django 3.0.3 on 2020-03-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200309_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookversion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
