# Generated by Django 3.0.3 on 2020-03-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20200309_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookversion',
            name='type',
        ),
    ]
