# Generated by Django 3.0.3 on 2020-03-09 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0011_remove_bookversion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[[0, 'In plans'], [1, 'In progress'], [2, 'Completed'], [3, 'Dropped']])),
                ('type', models.PositiveSmallIntegerField(choices=[[0, 'ebook'], [1, 'audio'], [2, 'paper']])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='bookversion',
            old_name='name',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='BookStatus',
        ),
        migrations.AddField(
            model_name='bookstate',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='book.BookVersion'),
        ),
        migrations.AddField(
            model_name='bookstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
