# Generated by Django 3.0.3 on 2020-03-09 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0014_auto_20200309_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[[0, 'In plans'], [1, 'In progress'], [2, 'Completed'], [3, 'Dropped']])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='book.BookIdentifier'),
        ),
        migrations.AddField(
            model_name='bookversion',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[[0, 'ebook'], [1, 'audio'], [2, 'paper']], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookState',
        ),
        migrations.AddField(
            model_name='bookuserstatus',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='book.BookVersion'),
        ),
        migrations.AddField(
            model_name='bookuserstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
