# Generated by Django 3.0.3 on 2020-03-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20200309_0541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookidentifier',
            unique_together={('book', 'type')},
        ),
    ]
