# Generated by Django 3.0.3 on 2020-03-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20200310_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookversion',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookversion',
            name='seconds_length',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookversion',
            unique_together=set(),
        ),
    ]
