# Generated by Django 3.0.3 on 2020-03-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_auto_20200310_0342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shelfbookitem',
            unique_together={('shelf', 'book')},
        ),
    ]
