# Generated by Django 3.0.3 on 2020-03-10 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_auto_20200310_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcompletedsummary',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
