# Generated by Django 3.0.3 on 2020-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_remove_series_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookversion',
            name='type',
        ),
        migrations.AddField(
            model_name='bookcompletedsummary',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[[0, 'ebook'], [1, 'audio'], [2, 'paper']], default=1),
            preserve_default=False,
        ),
    ]
