# Generated by Django 3.0.3 on 2020-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_auto_20200310_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorversion',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
