# Generated by Django 3.0.3 on 2020-03-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_auto_20200312_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[[0, 'Goodreads'], [1, 'Fantlab'], [2, 'Librarything'], [3, 'Amazon']])),
                ('external_id', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author')),
            ],
            options={
                'unique_together': {('author', 'type')},
            },
        ),
    ]
