# Generated by Django 3.0.3 on 2020-03-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0040_auto_20200312_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoridentifier',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[[0, 'Goodreads'], [1, 'Fantlab'], [2, 'Librarything'], [4, 'Author Today']]),
        ),
    ]
