# Generated by Django 3.0.3 on 2020-04-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0042_auto_20200312_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookusertimeline',
            options={'ordering': ['created', 'id']},
        ),
    ]
