# Generated by Django 3.0.3 on 2020-03-09 02:33

from django.db import migrations


def initial_data(apps, schema_editor):
    Language = apps.get_model('base', 'Language')
    Language.objects.create(name='Russian', code='RUS', order=0)
    Language.objects.create(name='English', code='ENG', order=1)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]
