# Generated by Django 3.0.3 on 2020-03-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200309_0233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Identifier',
        ),
        migrations.RemoveField(
            model_name='series',
            name='language',
        ),
        migrations.RemoveField(
            model_name='seriesversion',
            name='language',
        ),
        migrations.RemoveField(
            model_name='seriesversion',
            name='series',
        ),
    ]
