# Generated by Django 3.0.3 on 2020-03-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200309_0253'),
        ('base', '0003_auto_20200309_0253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shelf',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='SeriesVersion',
        ),
    ]
