# Generated by Django 3.0.3 on 2020-03-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_language_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['order']},
        ),
    ]
