# Generated by Django 3.0.3 on 2020-03-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[[0, 'ebook'], [1, 'audio'], [2, 'paper']])),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShelfBookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelfs', to='book.BookEdition')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Shelf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesBookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=4)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookEdition')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Series')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[[0, 'In plans'], [1, 'In progress'], [2, 'Completed'], [3, 'Dropped']])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='book.BookEdition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookOriginal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('original_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Language')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
