# Generated by Django 3.0.3 on 2020-03-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200309_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriesversion',
            options={'ordering': ['language__order']},
        ),
        migrations.AddField(
            model_name='bookedition',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bookoriginal',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookoriginal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
