# Generated by Django 3.0.3 on 2020-03-09 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_person'),
        ('book', '0005_auto_20200309_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='BookEdition',
            new_name='BookVersion',
        ),
        migrations.RemoveField(
            model_name='author',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='language',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='series',
            name='language',
        ),
        migrations.RemoveField(
            model_name='series',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='original_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesversion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BookOriginal',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='book.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='original_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Country'),
        ),
    ]
