# Generated by Django 3.0.3 on 2020-03-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200309_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
    ]
