# Generated by Django 3.0.3 on 2020-03-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_person'),
        ('book', '0013_auto_20200309_0446'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorversion',
            unique_together={('entity', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='bookversion',
            unique_together={('entity', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='seriesversion',
            unique_together={('entity', 'language')},
        ),
    ]
