# Generated by Django 3.0.3 on 2020-03-09 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20200309_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='identifiers',
        ),
        migrations.AddField(
            model_name='bookidentifier',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='book.Book'),
            preserve_default=False,
        ),
    ]
