# Generated by Django 3.0.3 on 2020-03-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_shelf_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
