# Generated by Django 3.0.3 on 2020-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20200310_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
