# Generated by Django 3.0.3 on 2020-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_series_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
