# Generated by Django 3.0.3 on 2020-03-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_auto_20200310_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='order',
        ),
    ]
