# Generated by Django 3.0.3 on 2020-03-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_authorversion_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesversion',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
