# Generated by Django 3.0.3 on 2020-03-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_seriesversion_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookversion',
            old_name='is_original',
            new_name='is_main',
        ),
    ]
