# Generated by Django 3.0.3 on 2020-03-12 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_auto_20200311_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookusertimeline',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='bookcompletedsummary',
            name='finished',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookusertimeline',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookusertimeline',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='book.BookVersion'),
        ),
        migrations.AlterField(
            model_name='bookusertimeline',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[[1, 'Started'], [2, 'Completed'], [3, 'Dropped']]),
        ),
    ]
