# Generated by Django 3.0.3 on 2020-03-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_auto_20200312_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookusertimeline',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='bookcompletedsummary',
            name='finished',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookusertimeline',
            name='created',
            field=models.DateField(),
        ),
    ]
