# Generated by Django 3.0.3 on 2020-03-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_auto_20200312_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcompletedsummary',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='book.BookVersion'),
        ),
    ]
