# Generated by Django 3.0.3 on 2020-03-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0039_authoridentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoridentifier',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[[0, 'Goodreads'], [1, 'Fantlab'], [2, 'Librarything'], [3, 'Amazon'], [4, 'Author Today']]),
        ),
    ]
