# Generated by Django 3.0.3 on 2020-03-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0041_auto_20200312_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoridentifier',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='book.Author'),
        ),
    ]
