/* tslint:disable */
/* eslint-disable */
/**
 * Keeper
 * Project to keep information about read/watched books/comics/cinema/tv-shows/etc, and other different stuff (like personal bookkeeping).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance } from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { AuthRequest } from "../models";
// @ts-ignore
import { HTTPValidationError } from "../models";
// @ts-ignore
import { Token } from "../models";
/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Get user token by username and password
     * @summary Authenticate
     * @param {AuthRequest} authRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticateAuthPost: async (
      authRequest: AuthRequest,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'authRequest' is not null or undefined
      if (authRequest === null || authRequest === undefined) {
        throw new RequiredError(
          "authRequest",
          "Required parameter authRequest was null or undefined when calling authenticateAuthPost."
        );
      }
      const localVarPath = `/auth/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      const queryParameters = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        queryParameters.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        queryParameters.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(queryParameters).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const nonString = typeof authRequest !== "string";
      const needsSerialization =
        nonString && configuration && configuration.isJsonMime
          ? configuration.isJsonMime(
              localVarRequestOptions.headers["Content-Type"]
            )
          : nonString;
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(authRequest !== undefined ? authRequest : {})
        : authRequest || "";

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function (configuration?: Configuration) {
  return {
    /**
     * Get user token by username and password
     * @summary Authenticate
     * @param {AuthRequest} authRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticateAuthPost(
      authRequest: AuthRequest,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Token>
    > {
      const localVarAxiosArgs = await AuthApiAxiosParamCreator(
        configuration
      ).authenticateAuthPost(authRequest, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: (configuration?.basePath || basePath) + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     * Get user token by username and password
     * @summary Authenticate
     * @param {AuthRequest} authRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticateAuthPost(
      authRequest: AuthRequest,
      options?: any
    ): AxiosPromise<Token> {
      return AuthApiFp(configuration)
        .authenticateAuthPost(authRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
  /**
   * Get user token by username and password
   * @summary Authenticate
   * @param {AuthRequest} authRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public authenticateAuthPost(authRequest: AuthRequest, options?: any) {
    return AuthApiFp(this.configuration)
      .authenticateAuthPost(authRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
