/* tslint:disable */
/* eslint-disable */
/**
 * Keeper
 * Project to keep information about read/watched books/comics/cinema/tv-shows/etc, and other different stuff (like personal bookkeeping).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance } from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { AuthRequest } from "../models";
// @ts-ignore
import { HTTPValidationError } from "../models";
// @ts-ignore
import { Token } from "../models";
/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Get user token by username and password
     * @summary Authenticate
     * @param {AuthRequest} authRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticateAuthPost: async (
      authRequest: AuthRequest,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'authRequest' is not null or undefined
      assertParamExists("authenticateAuthPost", "authRequest", authRequest);
      const localVarPath = `/auth/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        authRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration);
  return {
    /**
     * Get user token by username and password
     * @summary Authenticate
     * @param {AuthRequest} authRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticateAuthPost(
      authRequest: AuthRequest,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Token>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.authenticateAuthPost(
        authRequest,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = AuthApiFp(configuration);
  return {
    /**
     * Get user token by username and password
     * @summary Authenticate
     * @param {AuthRequest} authRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticateAuthPost(
      authRequest: AuthRequest,
      options?: any
    ): AxiosPromise<Token> {
      return localVarFp
        .authenticateAuthPost(authRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
  /**
   * Get user token by username and password
   * @summary Authenticate
   * @param {AuthRequest} authRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public authenticateAuthPost(authRequest: AuthRequest, options?: any) {
    return AuthApiFp(this.configuration)
      .authenticateAuthPost(authRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
