# Generated by Django 3.0.3 on 2020-03-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200309_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
