name: Linters and Tests
on: [push]
jobs:
  lint_and_test:
    name: Run linters and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker container
        run: make build-docker

      - name: Lint code
        run: make lint

      - name: Run unit tests
        run: make test
